#!/usr/bin/bash
#

#
# #########################
# Purpose: Parse a configuration file for creating and building CTSM cases
# Author: Adrianna C. Foster
# Date: August, 2021
# bash version 4.2.46
# #########################
# #########################
# Input format: text file
# #########################
# #########################
# Notes: If you want to add more parameters, you must add it to the config
#        array and the variable list at the bottom of the file.

## Parameters set here ---------------------------------------------------------
# MACH              - machine (izumi/cheyenne)
# PROJECT           - project code
# SRCDIR            - CTSM source code directory
# TAG               - name of case
# CASE_DIR          - case directory path
# USER_MODS         - user mods direcotry path
# COMP              - compset for run
# RES               - resolution of run

## Config file name
conf=$1

## Set up the array
## Add more parameters here
typeset -A config
config=(
    [MACH]=""
    [SRCDIR]=""
    [CASE_NAME]=""
    [CASE_DIR]=""
    [USER_MODS]=""
    [COMPSET]=""
    [RES]=""
    [OUTDIR]=""
)

## Parse config file
while read line
do
    if echo $line | grep -F = &>/dev/null
    then
        varname=$(echo "$line" | cut -d '=' -f 1)
        config[$varname]=$(echo "$line" | cut -d '=' -f 2- | envsubst)
    fi
done < $conf

## Create variables - add more parameters here
MACH=${config[MACH]}
SRCDIR=${config[SRCDIR]}
CASE_NAME=${config[CASE_NAME]}
CASE_DIR=${config[CASE_DIR]}
USER_MODS=${config[USER_MODS]}
COMPSET=${config[COMPSET]}
RES=${config[RES]}
OUTDIR=${config[OUTDIR]}

