#!/usr/bin/bash
#

#
# #########################
# Purpose: Create and build a case for CTSM runs
# Author: Adrianna C. Foster
# Date: August, 2021
# bash version
# #########################
# #########################
# Input format: text file
# #########################
# #########################
# Notes: Makes use of the config_parse script. If you want to add more
#        parameters, see the notes for that script.

## Config file name
conf=$1

## Parse the config file
source config_parse ${conf}

## Get CTSM git version
cd ${SRCDIR}
githashctsm=`git log -n 1 --format=%h`

## Create case name
case_name=${CASE_DIR}/${TAG}_${githashctsm}

## Define CIME directory
base_dir=${SRCDIR}/cime/scripts

## Create the case
cd ${base_dir}
./create_newcase --case ${case_name} --res ${RES} --compset ${COMP} --project ${PROJECT} --run-unsupported --mach ${MACH}

## Set up and build
cd ${case_name}
./case.setup
./case.build

## Modify some parameters - can add more parameters using the config_parse
## script
## Note for variables that require quotes you must use the double then single
## quotes approach for it to work.
./xmlchange --id STOP_N --val ${STOPN}
./xmlchange --id RUN_STARTDATE --val "'$STARTDATE'"
./xmlchange --id STOP_OPTION --val ${STOPVAL}
./xmlchange --id CLM_FORCE_COLDSTART --val on
./xmlchange --id JOB_QUEUE --val verylong
./xmlchange --id DATM_CLMNCEP_YR_START --val ${DATMSTARTYR}
./xmlchange --id DATM_CLMNCEP_YR_END --val ${DATMSTOPYR}
